name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
        description: 'A GitHub Action to deploy an artifact as a GitHub Pages site'
    author: 'GitHub'
    runs:
      using: 'node16'
      main: 'dist/index.js'
    inputs:
      token:
        description: 'GitHub token'
        default: ${{ github.token }}
        required: true
      timeout:
        description: 'Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)'
        required: false
        default: '600000'
      error_count:
        description: 'Maximum number of status report errors before cancelling a deployment (default: 10)'
        required: false
        default: '10'
      reporting_interval:
        description: 'Time in milliseconds between two deployment status report (default: 5 seconds)'
        required: false
        default: '5000'
      artifact_name:
        description: 'Name of the artifact to deploy'
        required: false
        default: 'github-pages'
      preview:
        description: 'Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)'
        required: false
        default: 'false'
    outputs:
      page_url:
        description: 'URL to deployed GitHub Pages'
